/**
 * excel.ts — Lightweight Excel / CSV export utility for Kinetic.
 * Triggers a clean browser download of a CSV file that opens natively in Microsoft Excel & Google Sheets without corruption warnings.
 */

export interface ExcelColumn {
  header: string;
  key: string;
  width?: number;
}

/**
 * Export an array of objects to a downloadable Excel-compatible CSV spreadsheet.
 */
export function exportToExcel(
  rows: Record<string, unknown>[],
  filename: string,
  columns?: ExcelColumn[],
  sheetTitle?: string,
): void {
  if (!rows.length) {
    console.warn("exportToExcel: no rows to export");
    return;
  }

  const keys = columns ? columns.map((c) => c.key) : Object.keys(rows[0]);
  const headers = columns ? columns.map((c) => c.header) : keys;

  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
  const cleanFilename = filename.replace(/\.(xlsx|csv|xls)$/i, "");

  // Build CSV lines
  const lines: string[] = [];

  // Title block
  if (sheetTitle) {
    lines.push(escapeCsv(`KENETIC — ${sheetTitle}`));
    lines.push(escapeCsv(`Exported: ${now}`));
    lines.push(""); // blank separator
  }

  // Header row
  lines.push(headers.map(escapeCsv).join(","));

  // Data rows
  for (const row of rows) {
    lines.push(keys.map((k) => escapeCsv(String(row[k] ?? ""))).join(","));
  }

  // Footer summary
  lines.push("");
  lines.push(escapeCsv(`Total rows: ${rows.length}`));
  lines.push(escapeCsv(`Generated by Kenetic Construction Ops Platform`));

  // UTF-8 BOM (\uFEFF) ensures Excel opens non-ASCII characters and columns correctly
  const csvContent = "\uFEFF" + lines.join("\r\n");

  const blob = new Blob([csvContent], {
    type: "text/csv;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${cleanFilename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsv(value: string): string {
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}
