/**
 * excel.ts — Lightweight Excel (CSV-as-XLSX) export utility for Kinetic.
 * No external dependencies. Triggers a browser download of an .xlsx-compatible file.
 */

export interface ExcelColumn {
  header: string;
  key: string;
  width?: number;
}

/**
 * Export an array of objects to a downloadable Excel-compatible CSV file.
 * The file opens correctly in Microsoft Excel and Google Sheets.
 */
export function exportToExcel(
  rows: Record<string, unknown>[],
  filename: string,
  columns?: ExcelColumn[],
  sheetTitle?: string
): void {
  if (!rows.length) {
    console.warn("exportToExcel: no rows to export");
    return;
  }

  const keys = columns ? columns.map((c) => c.key) : Object.keys(rows[0]);
  const headers = columns ? columns.map((c) => c.header) : keys;

  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

  // Build CSV lines
  const lines: string[] = [];

  // Title row (merged visually in Excel when opened)
  if (sheetTitle) {
    lines.push(escapeCsv(`KINETIC — ${sheetTitle}`));
    lines.push(escapeCsv(`Exported: ${now}`));
    lines.push(""); // blank separator
  }

  // Header row
  lines.push(headers.map(escapeCsv).join(","));

  // Data rows
  for (const row of rows) {
    lines.push(keys.map((k) => escapeCsv(String(row[k] ?? ""))).join(","));
  }

  // Totals footer spacer
  lines.push("");
  lines.push(escapeCsv(`Total rows: ${rows.length}`));
  lines.push(escapeCsv(`Generated by Kinetic Construction Ops Platform`));

  const csvContent = "\uFEFF" + lines.join("\r\n"); // BOM for Excel UTF-8

  const blob = new Blob([csvContent], {
    type: "application/vnd.ms-excel;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsv(value: string): string {
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}
