/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdWarehouseRouteImport } from './routes/projects/$projectId/warehouse'
import { Route as ProjectsProjectIdSupervisorsRouteImport } from './routes/projects/$projectId/supervisors'
import { Route as ProjectsProjectIdSubcontractorsRouteImport } from './routes/projects/$projectId/subcontractors'
import { Route as ProjectsProjectIdReportsRouteImport } from './routes/projects/$projectId/reports'
import { Route as ProjectsProjectIdProgressRouteImport } from './routes/projects/$projectId/progress'
import { Route as ProjectsProjectIdPayrollRouteImport } from './routes/projects/$projectId/payroll'
import { Route as ProjectsProjectIdPaymentsRouteImport } from './routes/projects/$projectId/payments'
import { Route as ProjectsProjectIdMaterialsRouteImport } from './routes/projects/$projectId/materials'
import { Route as ProjectsProjectIdLogisticsRouteImport } from './routes/projects/$projectId/logistics'
import { Route as ProjectsProjectIdLabourRouteImport } from './routes/projects/$projectId/labour'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects/$projectId/issues'
import { Route as ProjectsProjectIdInspectionsRouteImport } from './routes/projects/$projectId/inspections'
import { Route as ProjectsProjectIdExpensesRouteImport } from './routes/projects/$projectId/expenses'
import { Route as ProjectsProjectIdEquipmentRouteImport } from './routes/projects/$projectId/equipment'
import { Route as ProjectsProjectIdDrawingsRouteImport } from './routes/projects/$projectId/drawings'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdBoqRouteImport } from './routes/projects/$projectId/boq'
import { Route as ProjectsProjectIdBillsRouteImport } from './routes/projects/$projectId/bills'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWarehouseRoute =
  ProjectsProjectIdWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSupervisorsRoute =
  ProjectsProjectIdSupervisorsRouteImport.update({
    id: '/supervisors',
    path: '/supervisors',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSubcontractorsRoute =
  ProjectsProjectIdSubcontractorsRouteImport.update({
    id: '/subcontractors',
    path: '/subcontractors',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdReportsRoute =
  ProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdProgressRoute =
  ProjectsProjectIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPayrollRoute =
  ProjectsProjectIdPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPaymentsRoute =
  ProjectsProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdMaterialsRoute =
  ProjectsProjectIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLogisticsRoute =
  ProjectsProjectIdLogisticsRouteImport.update({
    id: '/logistics',
    path: '/logistics',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLabourRoute = ProjectsProjectIdLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdInspectionsRoute =
  ProjectsProjectIdInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExpensesRoute =
  ProjectsProjectIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEquipmentRoute =
  ProjectsProjectIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDrawingsRoute =
  ProjectsProjectIdDrawingsRouteImport.update({
    id: '/drawings',
    path: '/drawings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBoqRoute = ProjectsProjectIdBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBillsRoute = ProjectsProjectIdBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/bills': typeof ProjectsProjectIdBillsRoute
  '/projects/$projectId/boq': typeof ProjectsProjectIdBoqRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/equipment': typeof ProjectsProjectIdEquipmentRoute
  '/projects/$projectId/expenses': typeof ProjectsProjectIdExpensesRoute
  '/projects/$projectId/inspections': typeof ProjectsProjectIdInspectionsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/logistics': typeof ProjectsProjectIdLogisticsRoute
  '/projects/$projectId/materials': typeof ProjectsProjectIdMaterialsRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/payroll': typeof ProjectsProjectIdPayrollRoute
  '/projects/$projectId/progress': typeof ProjectsProjectIdProgressRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/subcontractors': typeof ProjectsProjectIdSubcontractorsRoute
  '/projects/$projectId/supervisors': typeof ProjectsProjectIdSupervisorsRoute
  '/projects/$projectId/warehouse': typeof ProjectsProjectIdWarehouseRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/bills': typeof ProjectsProjectIdBillsRoute
  '/projects/$projectId/boq': typeof ProjectsProjectIdBoqRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/equipment': typeof ProjectsProjectIdEquipmentRoute
  '/projects/$projectId/expenses': typeof ProjectsProjectIdExpensesRoute
  '/projects/$projectId/inspections': typeof ProjectsProjectIdInspectionsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/logistics': typeof ProjectsProjectIdLogisticsRoute
  '/projects/$projectId/materials': typeof ProjectsProjectIdMaterialsRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/payroll': typeof ProjectsProjectIdPayrollRoute
  '/projects/$projectId/progress': typeof ProjectsProjectIdProgressRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/subcontractors': typeof ProjectsProjectIdSubcontractorsRoute
  '/projects/$projectId/supervisors': typeof ProjectsProjectIdSupervisorsRoute
  '/projects/$projectId/warehouse': typeof ProjectsProjectIdWarehouseRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/bills': typeof ProjectsProjectIdBillsRoute
  '/projects/$projectId/boq': typeof ProjectsProjectIdBoqRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/equipment': typeof ProjectsProjectIdEquipmentRoute
  '/projects/$projectId/expenses': typeof ProjectsProjectIdExpensesRoute
  '/projects/$projectId/inspections': typeof ProjectsProjectIdInspectionsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/logistics': typeof ProjectsProjectIdLogisticsRoute
  '/projects/$projectId/materials': typeof ProjectsProjectIdMaterialsRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/payroll': typeof ProjectsProjectIdPayrollRoute
  '/projects/$projectId/progress': typeof ProjectsProjectIdProgressRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/subcontractors': typeof ProjectsProjectIdSubcontractorsRoute
  '/projects/$projectId/supervisors': typeof ProjectsProjectIdSupervisorsRoute
  '/projects/$projectId/warehouse': typeof ProjectsProjectIdWarehouseRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/organizations'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/bills'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/inspections'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/logistics'
    | '/projects/$projectId/materials'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/payroll'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/subcontractors'
    | '/projects/$projectId/supervisors'
    | '/projects/$projectId/warehouse'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/organizations'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/projects'
    | '/projects/$projectId/bills'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/inspections'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/logistics'
    | '/projects/$projectId/materials'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/payroll'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/subcontractors'
    | '/projects/$projectId/supervisors'
    | '/projects/$projectId/warehouse'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/organizations'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/bills'
    | '/projects/$projectId/boq'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/inspections'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/logistics'
    | '/projects/$projectId/materials'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/payroll'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/subcontractors'
    | '/projects/$projectId/supervisors'
    | '/projects/$projectId/warehouse'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VendorsRoute: typeof VendorsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/warehouse': {
      id: '/projects/$projectId/warehouse'
      path: '/warehouse'
      fullPath: '/projects/$projectId/warehouse'
      preLoaderRoute: typeof ProjectsProjectIdWarehouseRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/supervisors': {
      id: '/projects/$projectId/supervisors'
      path: '/supervisors'
      fullPath: '/projects/$projectId/supervisors'
      preLoaderRoute: typeof ProjectsProjectIdSupervisorsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/subcontractors': {
      id: '/projects/$projectId/subcontractors'
      path: '/subcontractors'
      fullPath: '/projects/$projectId/subcontractors'
      preLoaderRoute: typeof ProjectsProjectIdSubcontractorsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reports': {
      id: '/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof ProjectsProjectIdReportsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/progress': {
      id: '/projects/$projectId/progress'
      path: '/progress'
      fullPath: '/projects/$projectId/progress'
      preLoaderRoute: typeof ProjectsProjectIdProgressRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/payroll': {
      id: '/projects/$projectId/payroll'
      path: '/payroll'
      fullPath: '/projects/$projectId/payroll'
      preLoaderRoute: typeof ProjectsProjectIdPayrollRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/payments': {
      id: '/projects/$projectId/payments'
      path: '/payments'
      fullPath: '/projects/$projectId/payments'
      preLoaderRoute: typeof ProjectsProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/materials': {
      id: '/projects/$projectId/materials'
      path: '/materials'
      fullPath: '/projects/$projectId/materials'
      preLoaderRoute: typeof ProjectsProjectIdMaterialsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/logistics': {
      id: '/projects/$projectId/logistics'
      path: '/logistics'
      fullPath: '/projects/$projectId/logistics'
      preLoaderRoute: typeof ProjectsProjectIdLogisticsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/labour': {
      id: '/projects/$projectId/labour'
      path: '/labour'
      fullPath: '/projects/$projectId/labour'
      preLoaderRoute: typeof ProjectsProjectIdLabourRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/inspections': {
      id: '/projects/$projectId/inspections'
      path: '/inspections'
      fullPath: '/projects/$projectId/inspections'
      preLoaderRoute: typeof ProjectsProjectIdInspectionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/expenses': {
      id: '/projects/$projectId/expenses'
      path: '/expenses'
      fullPath: '/projects/$projectId/expenses'
      preLoaderRoute: typeof ProjectsProjectIdExpensesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/equipment': {
      id: '/projects/$projectId/equipment'
      path: '/equipment'
      fullPath: '/projects/$projectId/equipment'
      preLoaderRoute: typeof ProjectsProjectIdEquipmentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/drawings': {
      id: '/projects/$projectId/drawings'
      path: '/drawings'
      fullPath: '/projects/$projectId/drawings'
      preLoaderRoute: typeof ProjectsProjectIdDrawingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/boq': {
      id: '/projects/$projectId/boq'
      path: '/boq'
      fullPath: '/projects/$projectId/boq'
      preLoaderRoute: typeof ProjectsProjectIdBoqRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/bills': {
      id: '/projects/$projectId/bills'
      path: '/bills'
      fullPath: '/projects/$projectId/bills'
      preLoaderRoute: typeof ProjectsProjectIdBillsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBillsRoute: typeof ProjectsProjectIdBillsRoute
  ProjectsProjectIdBoqRoute: typeof ProjectsProjectIdBoqRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdDrawingsRoute: typeof ProjectsProjectIdDrawingsRoute
  ProjectsProjectIdEquipmentRoute: typeof ProjectsProjectIdEquipmentRoute
  ProjectsProjectIdExpensesRoute: typeof ProjectsProjectIdExpensesRoute
  ProjectsProjectIdInspectionsRoute: typeof ProjectsProjectIdInspectionsRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRoute
  ProjectsProjectIdLabourRoute: typeof ProjectsProjectIdLabourRoute
  ProjectsProjectIdLogisticsRoute: typeof ProjectsProjectIdLogisticsRoute
  ProjectsProjectIdMaterialsRoute: typeof ProjectsProjectIdMaterialsRoute
  ProjectsProjectIdPaymentsRoute: typeof ProjectsProjectIdPaymentsRoute
  ProjectsProjectIdPayrollRoute: typeof ProjectsProjectIdPayrollRoute
  ProjectsProjectIdProgressRoute: typeof ProjectsProjectIdProgressRoute
  ProjectsProjectIdReportsRoute: typeof ProjectsProjectIdReportsRoute
  ProjectsProjectIdSubcontractorsRoute: typeof ProjectsProjectIdSubcontractorsRoute
  ProjectsProjectIdSupervisorsRoute: typeof ProjectsProjectIdSupervisorsRoute
  ProjectsProjectIdWarehouseRoute: typeof ProjectsProjectIdWarehouseRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBillsRoute: ProjectsProjectIdBillsRoute,
  ProjectsProjectIdBoqRoute: ProjectsProjectIdBoqRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
  ProjectsProjectIdDrawingsRoute: ProjectsProjectIdDrawingsRoute,
  ProjectsProjectIdEquipmentRoute: ProjectsProjectIdEquipmentRoute,
  ProjectsProjectIdExpensesRoute: ProjectsProjectIdExpensesRoute,
  ProjectsProjectIdInspectionsRoute: ProjectsProjectIdInspectionsRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRoute,
  ProjectsProjectIdLabourRoute: ProjectsProjectIdLabourRoute,
  ProjectsProjectIdLogisticsRoute: ProjectsProjectIdLogisticsRoute,
  ProjectsProjectIdMaterialsRoute: ProjectsProjectIdMaterialsRoute,
  ProjectsProjectIdPaymentsRoute: ProjectsProjectIdPaymentsRoute,
  ProjectsProjectIdPayrollRoute: ProjectsProjectIdPayrollRoute,
  ProjectsProjectIdProgressRoute: ProjectsProjectIdProgressRoute,
  ProjectsProjectIdReportsRoute: ProjectsProjectIdReportsRoute,
  ProjectsProjectIdSubcontractorsRoute: ProjectsProjectIdSubcontractorsRoute,
  ProjectsProjectIdSupervisorsRoute: ProjectsProjectIdSupervisorsRoute,
  ProjectsProjectIdWarehouseRoute: ProjectsProjectIdWarehouseRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VendorsRoute: VendorsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
